// Generated by CoffeeScript 1.3.3
(function() {
  var readline, rl;

  readline = require('readline');

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  module.exports = function(msg, callback) {
    rl.resume();
    return rl.question(msg, function(answer) {
      rl.pause();
      return callback(answer);
    });
  };

}).call(this);
