// Generated by CoffeeScript 1.6.2
(function() {
  var readline, rl;

  readline = require("readline");

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.pause();

  module.exports = function(msg, callback) {
    return rl.question(msg, function(answer) {
      rl.pause();
      return callback(answer);
    });
  };

}).call(this);
